### ISSUE TITLE
SnIO missing log.

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-io#41]
The logger seems to be registered and configured correctly but it doesn't write anywhere.  The logger works well if it is configured in code for example:
``` csharp
.WriteTo.File("logs43/snio-.log", LogEventLevel.Verbose, rollingInterval: RollingInterval.Day)
```
The working verbose log complete configuration in code:
``` csharp
.ConfigureLogging((hostBuilder, loggingBuilder) =>
{
    loggingBuilder.ClearProviders();
    loggingBuilder.AddSerilog(new LoggerConfiguration()
        .ReadFrom.Configuration(hostBuilder.Configuration)
        .MinimumLevel.Verbose()
        .WriteTo.File("logs43/snio-.log", LogEventLevel.Verbose, rollingInterval: RollingInterval.Day)
        .CreateLogger());
})
```
**Expectation**: if the tool is registered as a dotnet tool and executed from the command line (3rd party dev scenario), it should create a local or global log.

**Comment by tusmester** [comment]
The issue is that the `appsettings` file is missing. We must make sure we include that in the package in a way that it is copied during installation wherever the tool is installed on the dev machine.
